[
  {
    "timestamp": "2025-05-15T09:46:30.573840",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe857339490>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T09:50:02.580283",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f093b45c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T09:52:42.384566",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09ae1842d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:15:42.998999",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e84e44fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:15:43.053570",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd72d6f4410>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:17:55.560175",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f776069a850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:17:56.656680",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4d438a190>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:20:11.429430",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6d7f37a9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:20:14.209587",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb50a2069d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:21:30.205897",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4ae290690>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:21:31.467252",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcaa141da90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:22:40.937182",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe68be1ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  },
  {
    "timestamp": "2025-05-15T10:22:43.089549",
    "message": "[AUTO CORRECTION ERROR]: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /cole_webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f428ed65ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
  }
]